{% set version = '0.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny.router
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny.router_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny.router/shiny.router_{{ version }}.tar.gz
  sha256: 7d444d38fad2d9ddd3e9d44428ca8e873f644e832fcbb3638840185e7b63e8fd

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-htmltools
    - r-rlang
    - r-shiny
  run:
    - r-base
    - r-glue
    - r-htmltools
    - r-rlang
    - r-shiny

test:
  commands:
    - $R -e "library('shiny.router')"           # [not win]
    - "\"%R%\" -e \"library('shiny.router')\""  # [win]

about:
  home: https://appsilon.github.io/shiny.router/, https://github.com/Appsilon/shiny.router
  license: MIT
  summary: It is a simple router for your Shiny apps. The router allows you to create dynamic
    web applications with real-time User Interface and easily share url to pages within
    your Shiny apps.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
